### ISSUE TITLE
Hiding the window?

### ISSUE THREAD

**Issue by carys-cc** [funkydude/LegionInvasionTimer#1]
Is there any way to hide the window when it's not in use?

**Comment by funkydude** [comment]
If by window you mean bar anchor, then you can lock it to hide it.

**Comment by funkydude** [comment]
@patrickchoi If that's the answer you were looking for, please close this.

**Comment by carys-cc** [comment]
Ah sorry was away for the weekend. I meant to hide the window itself. Since there’s a 3-4 hour gap between invasions, would be good to be able to toggle it vs. having it on screen all the time. 

On 15 August 2016 at 7:00:31 AM, funkydude (notifications@github.com) wrote:

@patrickchoi If that's the answer you were looking for, please close this.

**Comment by funkydude** [comment]
Unless opening the config and toggling an option to hide/show the window is something people would actually frequently do (seems unlikely) I don't think this will happen. I'm going to add an option to hide it in raid.

**Comment by funkydude** [comment]
@patrickchoi for what it's worth you can now use this script as a macro

`/run if LegionInvasionTimer:IsShown() then LegionInvasionTimer:Hide() else LegionInvasionTimer:Show() end`
