### ISSUE TITLE
Frame Location

### ISSUE THREAD

**Issue by Talyrius** [funkydude/LegionInvasionTimer#32]
Will you consider saving the frame's `SetPoint` in _legionTimerDB_? I have the frame locked, so whenever I log into a new character, it's stuck in the center of my screen.

**Comment by funkydude** [comment]
I let WoW handle the positioning of this because I knew if I added it to the global options, it would be the one option people would start wanting separate per character, and I just don't see the point of going that in depth for a temporary addon. Even less so now there's less than a week.

**Comment by Talyrius** [comment]
I share my addons with friends and family and they're all complaining about it as well, but I understand your concern. I'll modify my local copy instead.
