### ISSUE TITLE
7.2.0 logging into an alt after logging in a main shows next countdown not current active timer

### ISSUE THREAD

**Issue by ceylina** [funkydude/LegionInvasionTimer#45]
So I logged into my main and it showed an active invasion which was great but once I logged into an alt, it showed "Next invasion 15hrs..." even though the current invasion still has 3 hours on it.

It almost seems like if you log into one character it will trigger the timer but once you log into another it treats the timer as up and triggers the next invasion countdown.

**Comment by funkydude** [comment]
Does this repeatedly happen or was it a one off?

**Comment by funkydude** [comment]
Re-open if it happens again with v7.2.1

**Comment by ceylina** [comment]
It's since been fixed with your last few updates. Looks like the upcoming timers are getting more accurate too

**Comment by funkydude** [comment]
Awesome, good to hear.
