### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by GoredToTears** [funkydude/LegionInvasionTimer#72]
If someone would have the time, you might be able to actually put the zone coming up next.  Both wowhead.com and worldofwarcraft.com forums have lists of the rotation Blizzard uses.  Would be nice to know if it was a zone with an emissary quest pending.

**Comment by funkydude** [comment]
wowhead does not tell you what the next zone will be, there is no way of knowing this.

**Comment by GoredToTears** [comment]
Yes, on both wowhead.com forums and on worldofwarcraft.com/community several people have posted and supposedly verified the rotation used.  I didn't say Wowhead knew or posted anything.  I stated it was in the forums where WoW players can post stuff.  But w/e.  I will just right it down and keep track for myself.
http://www.wowhead.com/forums&topic=276277&p=4126487

That is why I immediately started to write everything down and therefore discovered a pattern in the areas.   
   - Val'sharah
   - Stormheim
   - Azsuna
   - Highmountain
   
   - Stormheim
   - Highmountain
   - Val'sharah
   - Azsuna
   
   - Stormheim
   - Val'sharah
   - Highmountain
   - Azsuna
It has been verified by several reputable posters from the wowhead community.  I for one will be keeping track of it and verify it for myself.
    On Thursday, February 22, 2018, 4:32:13 PM CST, funkydude <notifications@github.com> wrote:  
 
 
Closed #72.
