### ISSUE TITLE
Is there a way to hide the chat spam ?

### ISSUE THREAD

**Issue by Jaladhjin** [funkydude/LegionInvasionTimer#73]
My chat's busy enough as is so I try to keep everything I can out of it :-)

**Comment by funkydude** [comment]
Define "chat spam"?

**Comment by Jaladhjin** [comment]
in 44 minutes I'll take a screenshot of the message it's posting in chat.

I just don't want the announce in chat.

The centered on screen message & my Titan Panel timers are enough for me :-)

**Comment by Jaladhjin** [comment]
![image](https://user-images.githubusercontent.com/26700663/38655815-55efbe8e-3ddc-11e8-83d5-18310fb9e4db.png)
